### ISSUE TITLE
path[0]がnilであることによるエラー

### ISSUE THREAD

**Issue by masayukiyasukawa** [masayukiyasukawa/training#1]
Traceback (most recent call last):
	1: from training1.rb:46:in `<main>'
training1.rb:35:in `proc': undefined method `+' for nil:NilClass (NoMethodError)

**Comment by masayukiyasukawa** [comment]
正しい出力は「bsd=>mit」であるが、実際は「NoMethodError」となっている。この出力をしている箇所は「p path[0] + " => " + @data[path[0]].to_s」である。
